Update validate-semver.yaml

diff --git a/.github/workflows/validate-semver.yaml b/.github/workflows/validate-semver.yaml
--- a/.github/workflows/validate-semver.yaml
+++ b/.github/workflows/validate-semver.yaml
@@ -1,1 +1,22 @@
-
+name: Validate Semantic Versioning
+on:
+  workflow_dispatch:
+    inputs:
+      version:
+        description: 'ENTAA A BAAZYON (TATOEBA v1.0.0)'
+        required: true
+        type: string
+jobs:
+  validate-tag:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate Semantic Version
+        id: validate-version
+        run: |
+          VERSION=${{github.event.inputs.version}}
+          SEMVER_REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
+          if [[ ! "$VERSION" =~ $SEMVER_REGEX ]]; then
+            echo "Invalid version: ${VERSION}"
+            exit 1
+          fi
+          echo "Version is valid: ${VERSION}"
